services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
      args:
        - PORT=${SERVICE_API_GATEWAY_HTTP_PORT}
    environment:
      - SERVICE_API_GATEWAY_HTTP_PORT=${SERVICE_API_GATEWAY_HTTP_PORT}
    ports:
      - "${SERVICE_API_GATEWAY_HTTP_PORT}:${SERVICE_API_GATEWAY_HTTP_PORT}"
    depends_on:
      - shared-deps

  catalogue:
    build:
      context: .
      dockerfile: apps/catalogue/Dockerfile
      args:
        - PORT=${SERVICE_CATALOGUE_TCP_PORT}
    environment:
      - SERVICE_CATALOGUE_TCP_PORT=${SERVICE_CATALOGUE_TCP_PORT}
    ports:
      - "${SERVICE_CATALOGUE_TCP_PORT}:${SERVICE_CATALOGUE_TCP_PORT}"
    depends_on:
      - shared-deps

  shared-deps:
    build:
      context: .
      target: base
    image: edigitax-base
    command: echo "Base image built"
