services:
  catalogue:
    build:
      context: .
      dockerfile: apps/catalogue/Dockerfile
      args:
        - PORT=${SERVICE_CATALOGUE_TCP_PORT}
    networks:
      app-network:
        aliases:
          - ${SERVICE_CATALOGUE_NAMESPACE}
    depends_on:
      db:
        condition: service_healthy
      shared-deps:
        condition: service_started

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
      args:
        - PORT=${SERVICE_API_GATEWAY_HTTP_PORT}
    networks:
      - app-network
    ports:
      - "${SERVICE_API_GATEWAY_HTTP_PORT}:${SERVICE_API_GATEWAY_HTTP_PORT}"
    depends_on:
      - shared-deps

  shared-deps:
    build:
      context: .
      target: base
    image: edigitax-base
    command: echo "Base image built"

  db:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: postgres
    networks:
      app-network:
        aliases:
          - ${SERVICE_CATALOGUE_NAMESPACE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
